alias fishes="nvim ~/dotfiles/fish/.config/fish/fish_alias.fish"

export DOTS='~/dotfiles/'
export PYTH='~/dotfiles/python/python_course/'

alias aur="yay -Qq | grep"
alias btop="bashtop"
alias cl="clear"
alias clip="xclip -sel c <"
alias cp="cp -i"
alias dfi="df --si -T"
alias dots="y $DOTS"
alias egrep="egrep --color=auto"
alias ff="fastfetch -l arch_small"
alias gitdot="sh $DOTS/gitpush.sh"
alias grep="grep --color=auto"
alias hyprconf="sudo nvim $DOTS/hypr/.config/hypr/hyprland.conf"
#alias i3conf="sudo nvim $DOTS/i3/.config/i3/config"
alias kittyconf="nvim $DOTS/kitty/.config/kitty/kitty.conf"
alias ls="ls -lahc --color=auto"
alias mkdir="mkdir -p"
alias mv="mv -i"
#alias picom="picom --config $DOTS/picom/.config/picom/picom.conf"
alias please="sudo $(history -p !!)"
#alias poly="polybar & disown"
#alias polyoff="pkill polybar"
#alias rpoly="pkill polybar && polybar & disown"
alias pyth="y $PYTH"
alias sp="sudo pacman"
alias super="sudo"
alias nanos="sudo nano"
alias unstow="stow --delete"
alias waybar="waybar & disown"
alias wayboff="pkill waybar"
alias waybreset="pkill waybar && waybar & disown"
alias z="cd"
