alias fishes="nvim ~/dotfiles/fish/.config/fish/fish_alias.fish"
alias fishconf="nvim ~/dotfiles/fish/.config/fish/config.fish"

export DOTS='~/dotfiles/'
export PYTH='~/dotfiles/python/python_course/'

alias aur="yay -Qq | grep"
alias btop="bashtop"
alias cl="clear"
alias clip="xclip -sel c <"
alias cp="cp -i"
alias dfi="df --si -T"
alias dots="y $DOTS"
alias egrep="egrep --color=auto"
alias ff="fastfetch --data-raw '$(pokemon-colorscripts -n mudkip --no-title)'"
alias gitdot="sh $DOTS/gitpush.sh"
alias grep="grep --color=auto"
alias hyprconf="nvim $DOTS/hypr/.config/hypr/hyprland.conf"
alias i3conf="sudo nvim $DOTS/i3/.config/i3/config"
alias kittyconf="nvim $DOTS/kitty/.config/kitty/kitty.conf"
alias ls="ls -lahc --color=auto"
alias matrix="cmatrix -C blue"
alias mkdir="mkdir -p"
alias mv="mv -i"
alias nvimconf="nvim ~/dotfiles/neovim/.config/nvim/init.lua"
alias please="sudo $(history -p !!)"
alias pokemon="pokemon-colorscripts -n"
alias pyth="y $PYTH"
alias sp="sudo pacman"
alias super="sudo"
alias nanos="sudo nano"
alias unstow="stow --delete"
alias waybar="waybar & disown"
alias wayboff="pkill waybar"
alias waybreset="pkill waybar && waybar & disown"
alias waybconf="nvim ~/dotfiles/waybar/.config/waybar/config.jsonc"
alias waybst="nvim ~/dotfiles/waybar/.config/waybar/style.css"
alias yaziconf="nvim ~/dotfiles/yazi/.config/yazi/yazi.toml"
alias z="cd"
